[project]
name = "engineering-thesis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.3",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "sahi>=0.11.36",
    "scikit-learn>=1.8.0",
    "shapely>=2.1.2",
    "ultralytics>=8.4.47",
]

[tool.ruff]
line-length = 88
extend-exclude = ["*.ipynb", "**/migrations/*"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ANN001", "ANN201"] # ANN001: function args, ANN201: return types

[dependency-groups]
dev = [
    "djlint>=1.36.4",
    "ruff>=0.15.7",
]

[tool.djlint]
profile = "django"
indent = 2
