# Generated by Django 6.0.3 on 2026-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(help_text='{x, y, w, h, rotation}')),
                ('confidence', models.FloatField()),
                ('predicted_class', models.CharField(max_length=50)),
                ('area', models.FloatField(help_text='Pixel area of bbox; persisted to drive the seeds volume filter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unsure', 'Unsure')], default='pending', max_length=20)),
                ('flagged_for_training', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('model_file_path', models.CharField(max_length=255)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='e.g. {precision, recall, f1, mae, rmse, confusion_matrix}')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Hyperparameters and training config (model-specific shape)')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_log', models.TextField(blank=True)),
            ],
        ),
    ]
