# Generated by Django 6.0.5 on 2026-06-01 18:51

import apps.analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('reference_seeds', models.JSONField(blank=True, default=dict)),
                ('image_count', models.IntegerField(default=0)),
                ('processed_image_count', models.IntegerField(default=0)),
                ('detection_count', models.IntegerField(default=0)),
                ('failed_image_count', models.IntegerField(default=0)),
                ('detections_by_class', models.JSONField(blank=True, default=dict)),
                ('detections_by_source', models.JSONField(blank=True, default=dict)),
                ('activity_log', models.JSONField(blank=True, default=list, help_text='List of {time, message, level} entries appended by the worker')),
                ('error_message', models.TextField(blank=True)),
                ('review_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='inference_runs', to='datasets.imageasset')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_inference_runs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='datasets.upload')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(help_text='Source-image pixel coords: {x1, y1, x2, y2, w, h}. Written by the ML pipeline in ml-pipelines/pollinator/workflows.')),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('predicted_class', models.CharField(max_length=50)),
                ('area', models.FloatField(help_text='Pixel area of bbox; persisted to drive the seeds volume filter')),
                ('crop', models.ImageField(blank=True, help_text='Cropped bbox image, written after inference for review and training.', null=True, upload_to=apps.analysis.models.detection_crop_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unsure', 'Unsure')], default='pending', max_length=20)),
                ('reviewer_label', models.CharField(blank=True, help_text='Class assigned by a reviewer when correcting the prediction', max_length=50)),
                ('seed_status', models.CharField(blank=True, choices=[('active', 'Active'), ('aborted', 'Aborted'), ('reference', 'Reference')], max_length=20, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_accepted', models.BooleanField(default=False, help_text='True when the "Suggest exports" auto-select confirmed this detection because it cleared both confidence thresholds. Distinguishes machine-picked acceptances from manual reviewer confirmations: any manual review action clears it. Drives the blue (auto) vs green (manual) cue on the Export page.')),
                ('excluded_from_export', models.BooleanField(default=False, help_text='When True, this detection is hidden from the CSV export counts even if it was accepted by the reviewer. Used by the Export step to drop duplicates (same insect detected twice).')),
                ('export_exclusion_user_set', models.BooleanField(default=False, help_text='True once a reviewer has explicitly toggled excluded_from_export from the Export page. Engulfment auto-exclude skips these rows so a manual include/exclude decision is sticky across re-runs.')),
                ('exclude_from_training', models.BooleanField(default=False, help_text='Reviewer flag: exclude this crop from binary/group classifier training. Set by un-ticking the crop in the training pool drawer; the crop stays visible (greyed) and can be re-included. Distinct from excluded_from_export (which only affects CSV export) and from ImageAsset.exclude_from_training (which governs YOLO detector training at the image level).')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='datasets.imageasset')),
                ('reference_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_seeds', to='analysis.detection')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL)),
                ('inference_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='analysis.inferencerun')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20)),
                ('kind', models.CharField(blank=True, choices=[('detector', 'Detector'), ('binary_classifier', 'Binary classifier'), ('group_classifier', 'Group classifier')], max_length=20)),
                ('version_name', models.CharField(max_length=100)),
                ('model_file_path', models.CharField(help_text="Local path, 'file://...', 's3://bucket/key', or 'gs://bucket/key'.", max_length=512)),
                ('description', models.TextField(blank=True, help_text='Operator notes: dataset, training environment, anything worth remembering about this version.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Final metrics from the training run (val/test scores, per-class breakdowns, confusion-matrix counts).')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Hyperparameters and training config (model-specific shape).')),
                ('sample_count', models.PositiveIntegerField(blank=True, help_text='Number of training samples (crops or labeled images) used.', null=True)),
                ('training_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Wall-clock training duration in seconds.', null=True)),
                ('trained_at', models.DateTimeField(blank=True, help_text='When the underlying weights were trained. Distinct from created_at, which is when this row was registered.', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_versions', to=settings.AUTH_USER_MODEL)),
                ('source_model_version', models.ForeignKey(blank=True, help_text='If this model was trained as an incremental fine-tune, the ModelVersion whose weights were the starting point.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='analysis.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('training_curve', 'Training curve'), ('confusion_matrix', 'Confusion matrix'), ('pr_curve', 'Precision-Recall curve'), ('f1_curve', 'F1-Confidence curve'), ('precision_curve', 'Precision-Confidence curve'), ('recall_curve', 'Recall-Confidence curve'), ('sample_predictions', 'Sample predictions'), ('labels', 'Label distribution'), ('results_csv', 'Per-epoch metrics CSV'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to=apps.analysis.models.model_artifact_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analysis.modelversion')),
            ],
            options={
                'ordering': ['model_version', 'kind', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='model_version',
            field=models.ForeignKey(blank=True, help_text='Single-model FK for modules like seeds. Pollinator runs use config.{yolo,binary_classifier,group_classifier}.model_version_id inside the JSON config instead and leave this null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analysis.modelversion'),
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('image_count', models.IntegerField(default=0)),
                ('current_epoch', models.IntegerField(default=0)),
                ('total_epochs', models.IntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Live metrics for the running job (loss, val_f1/macro_f1, ...)')),
                ('activity_log', models.JSONField(blank=True, default=list, help_text='List of {time, message, level} entries appended by the worker')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_training_jobs', to=settings.AUTH_USER_MODEL)),
                ('resulting_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='analysis.modelversion')),
                ('training_detections', models.ManyToManyField(blank=True, related_name='training_jobs', to='analysis.detection')),
            ],
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['inference_run', 'status'], name='analysis_de_inferen_f4d996_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['image', 'predicted_class'], name='analysis_de_image_i_e003f2_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['area'], name='analysis_de_area_bcd352_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'is_active'], name='analysis_mo_module_1b7222_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'kind'], name='analysis_mo_module_baeadc_idx'),
        ),
        migrations.AddIndex(
            model_name='modelartifact',
            index=models.Index(fields=['model_version', 'kind'], name='analysis_mo_model_v_6cd231_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', '-created_at'], name='analysis_in_module_c32603_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'status'], name='analysis_in_module_cabcab_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'archived'], name='analysis_in_module_9331f6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['module', '-started_at'], name='analysis_tr_module_1bb11b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['module', 'status'], name='analysis_tr_module_a1dd8d_idx'),
        ),
    ]
