# Generated by Django 6.0.3 on 2026-05-10 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('kind', models.CharField(blank=True, choices=[('detector', 'Detector'), ('binary_classifier', 'Binary classifier'), ('group_classifier', 'Group classifier')], max_length=20)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('model_file_path', models.CharField(max_length=255)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='e.g. {precision, recall, f1, mae, rmse, confusion_matrix}')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Hyperparameters and training config (model-specific shape)')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('image_count', models.IntegerField(default=0)),
                ('processed_image_count', models.IntegerField(default=0)),
                ('detection_count', models.IntegerField(default=0)),
                ('failed_image_count', models.IntegerField(default=0)),
                ('detections_by_class', models.JSONField(blank=True, default=dict)),
                ('detections_by_source', models.JSONField(blank=True, default=dict)),
                ('activity_log', models.JSONField(blank=True, default=list, help_text='List of {time, message, level} entries appended by the worker')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='inference_runs', to='datasets.imageasset')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_inference_runs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='datasets.upload')),
                ('model_version', models.ForeignKey(blank=True, help_text='Single-model FK for modules like seeds. Pollinator runs use config.{yolo,binary_classifier,group_classifier}.model_version_id inside the JSON config instead and leave this null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analysis.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators'), ('pollen', 'Pollen'), ('flowers', 'Flowers')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_log', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_training_jobs', to=settings.AUTH_USER_MODEL)),
                ('resulting_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='analysis.modelversion')),
                ('training_images', models.ManyToManyField(blank=True, related_name='training_jobs', to='datasets.imageasset')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(help_text='{x, y, w, h, rotation}')),
                ('confidence', models.FloatField()),
                ('predicted_class', models.CharField(max_length=50)),
                ('area', models.FloatField(help_text='Pixel area of bbox; persisted to drive the seeds volume filter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unsure', 'Unsure')], default='pending', max_length=20)),
                ('reviewer_label', models.CharField(blank=True, help_text='Class assigned by a reviewer when correcting the prediction', max_length=50)),
                ('flagged_for_training', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='datasets.imageasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL)),
                ('inference_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='analysis.inferencerun')),
            ],
            options={
                'indexes': [models.Index(fields=['inference_run', 'status'], name='analysis_de_inferen_f4d996_idx'), models.Index(fields=['image', 'predicted_class'], name='analysis_de_image_i_e003f2_idx'), models.Index(fields=['flagged_for_training'], name='analysis_de_flagged_3dea76_idx'), models.Index(fields=['area'], name='analysis_de_area_bcd352_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'is_active'], name='analysis_mo_module_1b7222_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'kind'], name='analysis_mo_module_baeadc_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', '-created_at'], name='analysis_in_module_c32603_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'status'], name='analysis_in_module_cabcab_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'archived'], name='analysis_in_module_9331f6_idx'),
        ),
    ]
