# Generated by Django 6.0.3 on 2026-04-15 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='datasets.imageasset'),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='images',
            field=models.ManyToManyField(related_name='inference_runs', to='datasets.imageasset'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_inference_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detection',
            name='inference_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='analysis.inferencerun'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analysis.modelversion'),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_training_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='resulting_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='analysis.modelversion'),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='training_images',
            field=models.ManyToManyField(blank=True, related_name='training_jobs', to='datasets.imageasset'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['inference_run', 'status'], name='analysis_de_inferen_f4d996_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['image', 'predicted_class'], name='analysis_de_image_i_e003f2_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['flagged_for_training'], name='analysis_de_flagged_3dea76_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['area'], name='analysis_de_area_bcd352_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'is_active'], name='analysis_mo_module_1b7222_idx'),
        ),
    ]
