# Generated by Django 6.0.5 on 2026-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='exclude_from_training',
            field=models.BooleanField(default=False, help_text='Reviewer flag: exclude this crop from binary/group classifier training. Set by un-ticking the crop in the training pool drawer; the crop stays visible (greyed) and can be re-included. Distinct from excluded_from_export (which only affects CSV export) and from ImageAsset.include_in_training (which governs YOLO detector training at the image level).'),
        ),
    ]
