# Generated by Django 6.0.3 on 2026-04-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='common_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detection',
            name='confirmed',
            field=models.BooleanField(blank=True, help_text='InsectNet in-distribution flag (True = confident ID)', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='detection_scope',
            field=models.CharField(choices=[('roi', 'Inside ROI (near marked flower)'), ('outside_roi', 'Outside ROI'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='detection',
            name='energy_score',
            field=models.FloatField(blank=True, help_text='InsectNet OOD energy score; lower = more confident', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detection',
            name='near_marker',
            field=models.BooleanField(blank=True, help_text='Detection overlaps with the marked-flower ROI zone', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detection',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
