# Generated by Django 6.0.3 on 2026-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_detection_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='bbox',
            field=models.JSONField(help_text='Source-image pixel coords: {x1, y1, x2, y2, w, h}. Written by the ML pipeline in ml-pipelines/pollinator/workflows.'),
        ),
    ]
