# Generated by Django 6.0.3 on 2026-05-05 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_detection_common_name_detection_confirmed_and_more'),
        ('datasets', '0002_upload_imageasset_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen pipeline config: detector toggles, model_version IDs, thresholds.'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='datasets.upload'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='kind',
            field=models.CharField(choices=[('detector', 'Detector'), ('classifier', 'Classifier'), ('preprocessing', 'Preprocessing')], default='detector', max_length=20),
        ),
        migrations.AlterField(
            model_name='inferencerun',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='inference_runs', to='datasets.imageasset'),
        ),
        migrations.AlterField(
            model_name='inferencerun',
            name='model_version',
            field=models.ForeignKey(blank=True, help_text='Single-model runs (e.g. seeds). Multi-model runs use config.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analysis.modelversion'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'status'], name='analysis_in_module_cabcab_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['upload'], name='analysis_in_upload__e934ef_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['archived'], name='analysis_in_archive_9049f9_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'kind'], name='analysis_mo_module_baeadc_idx'),
        ),
    ]
