# Generated by Django 6.0.3 on 2026-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_detection_bbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='excluded_from_export',
            field=models.BooleanField(default=False, help_text='When True, this detection is hidden from the CSV export counts even if it was accepted by the reviewer. Used by the Export step to drop duplicates (same insect detected twice).'),
        ),
    ]
