# Generated by Django 6.0.3 on 2026-05-09 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_detection_common_name_detection_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='kind',
            field=models.CharField(blank=True, choices=[('detector', 'Detector'), ('classifier', 'Classifier')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['module', 'kind'], name='analysis_mo_module_baeadc_idx'),
        ),
    ]
