# Generated by Django 6.0.3 on 2026-05-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_modelversion_kind_and_more'),
        ('datasets', '0002_upload_imageasset_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencerun',
            name='model_version',
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='activity_log',
            field=models.JSONField(blank=True, default=list, help_text='List of {time, message, level} entries appended by the worker'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='detection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='detections_by_class',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='detections_by_source',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='failed_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='processed_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='datasets.upload'),
        ),
        migrations.AlterField(
            model_name='inferencerun',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='inference_runs', to='datasets.imageasset'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', '-created_at'], name='analysis_in_module_c32603_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'status'], name='analysis_in_module_cabcab_idx'),
        ),
    ]
