# Generated by Django 6.0.3 on 2026-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_detection_excluded_from_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='export_exclusion_user_set',
            field=models.BooleanField(default=False, help_text='True once a reviewer has explicitly toggled excluded_from_export from the Export page. Engulfment auto-exclude skips these rows so a manual include/exclude decision is sticky across re-runs.'),
        ),
    ]
