# Generated by Django 6.0.3 on 2026-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_inferencerun_archived_inferencerun_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
