# Generated by Django 6.0.4 on 2026-05-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_detection_export_exclusion_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='reference_detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_seeds', to='analysis.detection'),
        ),
        migrations.AddField(
            model_name='detection',
            name='seed_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('aborted', 'Aborted'), ('reference', 'Reference')], max_length=20, null=True),
        ),
    ]
