# Generated by Django 6.0.3 on 2026-05-09 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_inferencerun_model_version_and_more'),
        ('datasets', '0002_upload_imageasset_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='binary_confidence',
            field=models.FloatField(blank=True, help_text='InsectNet binary insect/background confidence', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='class_probs',
            field=models.JSONField(blank=True, default=dict, help_text='Per-class probability dict from the group classifier'),
        ),
        migrations.AddField(
            model_name='detection',
            name='insectnet_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detection',
            name='insectnet_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='merge_iou',
            field=models.FloatField(blank=True, help_text='IoU between YOLO and preprocessing bboxes when source=both', null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewer_label',
            field=models.CharField(blank=True, help_text='Class assigned by a reviewer when correcting the prediction', max_length=50),
        ),
        migrations.AddField(
            model_name='detection',
            name='source',
            field=models.CharField(blank=True, choices=[('yolo', 'YOLO only'), ('preprocessing', 'Preprocessing only'), ('both', 'Both detectors')], max_length=20),
        ),
        migrations.AddField(
            model_name='detection',
            name='yolo_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detection',
            name='yolo_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['inference_run', 'source'], name='analysis_de_inferen_1e80b4_idx'),
        ),
    ]
