# Generated by Django 6.0.4 on 2026-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_detection_reference_detection_detection_seed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='polygon',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
