# Generated by Django 6.0.3 on 2026-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_inferencerun_status_alter_trainingjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencerun',
            name='module',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='module',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='module',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('pollinators', 'Pollinators')], max_length=20),
        ),
    ]
