# Generated by Django 6.0.3 on 2026-05-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_detection_binary_confidence_detection_class_probs_and_more'),
        ('datasets', '0003_upload_status_upload_datasets_up_module_2aad32_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='model_version',
            field=models.ForeignKey(blank=True, help_text='Single-model FK for modules like seeds. Pollinator runs use config.yolo.model_version_id + config.classifier.model_version_id instead and leave this null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analysis.modelversion'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['module', 'archived'], name='analysis_in_module_9331f6_idx'),
        ),
    ]
