# Generated by Django 6.0.4 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_detection_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='reference_seeds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
