# Generated by Django 6.0.3 on 2026-05-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_inferencerun_module_alter_modelversion_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='review_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
