# Generated by Django 6.0.3 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_inferencerun_review_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='exclude_from_training',
            field=models.BooleanField(default=False),
        ),
    ]
