# Generated by Django 6.0.4 on 2026-05-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_inferencerun_reference_seeds'),
        ('analysis', '0009_detection_exclude_from_training'),
    ]

    operations = [
    ]
