# Generated by Django 6.0.5 on 2026-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_detection_exclude_from_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
