# Generated by Django 6.0.5 on 2026-05-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_detection_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='auto_accepted',
            field=models.BooleanField(default=False, help_text='True when the "Suggest exports" auto-select confirmed this detection because it cleared both confidence thresholds. Distinguishes machine-picked acceptances from manual reviewer confirmations: any manual review action clears it. Drives the blue (auto) vs green (manual) cue on the Export page.'),
        ),
    ]
