# Generated by Django 6.0.5 on 2026-05-28 21:35

import apps.analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_detection_auto_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='crop',
            field=models.ImageField(blank=True, help_text='Cropped bbox image, written after inference for review and training.', null=True, upload_to=apps.analysis.models.detection_crop_path),
        ),
    ]
