# Generated by Django 6.0.5 on 2026-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_detection_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='version_name',
            field=models.CharField(max_length=100),
        ),
    ]
