# Generated by Django 6.0.3 on 2026-05-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollinatorDetection',
            fields=[
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pollinator_detection', serialize=False, to='analysis.detection')),
                ('yolo_class', models.CharField(blank=True, max_length=50)),
                ('yolo_confidence', models.FloatField(blank=True, null=True)),
                ('insectnet_class', models.CharField(blank=True, max_length=50)),
                ('insectnet_confidence', models.FloatField(blank=True, null=True)),
                ('binary_confidence', models.FloatField(blank=True, help_text='InsectNet binary insect/background confidence', null=True)),
                ('class_probs', models.JSONField(blank=True, default=dict, help_text='Per-class probability dict from the group classifier')),
                ('source', models.CharField(blank=True, choices=[('yolo', 'YOLO only'), ('preprocessing', 'Preprocessing only'), ('both', 'Both detectors')], max_length=20)),
                ('merge_iou', models.FloatField(blank=True, help_text='IoU between YOLO and preprocessing bboxes when source=both', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='pollinator__source_5305ff_idx')],
            },
        ),
    ]
