from django.urls import path

from .views import (
    PollinatorDetectionDetailView,
    PollinatorDetectionListView,
    PollinatorDetectionSummaryView,
    PollinatorDetectorDatasetUploadView,
    PollinatorRunAutoSelectView,
    PollinatorRunExportAnnotatedView,
    PollinatorRunExportCropsView,
    PollinatorRunExportCSVView,
    PollinatorTrainingCreateView,
    PollinatorTrainingPoolView,
)

urlpatterns = [
    path(
        'runs/<int:run_id>/detections/',
        PollinatorDetectionListView.as_view(),
        name='pollinator-run-detections',
    ),
    path(
        'runs/<int:run_id>/detections/summary/',
        PollinatorDetectionSummaryView.as_view(),
        name='pollinator-run-detections-summary',
    ),
    path(
        'runs/<int:run_id>/auto-select/',
        PollinatorRunAutoSelectView.as_view(),
        name='pollinator-run-auto-select',
    ),
    path(
        'runs/<int:run_id>/export.csv',
        PollinatorRunExportCSVView.as_view(),
        name='pollinator-run-export-csv',
    ),
    path(
        'runs/<int:run_id>/export-crops.zip',
        PollinatorRunExportCropsView.as_view(),
        name='pollinator-run-export-crops',
    ),
    path(
        'runs/<int:run_id>/export-annotated.zip',
        PollinatorRunExportAnnotatedView.as_view(),
        name='pollinator-run-export-annotated',
    ),
    path(
        'detections/<int:pk>/',
        PollinatorDetectionDetailView.as_view(),
        name='pollinator-detection-detail',
    ),
    path(
        'training/',
        PollinatorTrainingCreateView.as_view(),
        name='pollinator-training-create',
    ),
    path(
        'training/pool/',
        PollinatorTrainingPoolView.as_view(),
        name='pollinator-training-pool',
    ),
    path(
        'training/detector-dataset/',
        PollinatorDetectorDatasetUploadView.as_view(),
        name='pollinator-detector-dataset-upload',
    ),
]
